package apidocs

import _ "embed"

//go:generate bash ../../../../scripts/contracts/sync-openapi-embed.sh

// openAPISource is generated byte-for-byte from
// packages/contracts/openapi.yaml, the repository's single contract source.
//
//go:embed openapi.yaml
var openAPISource []byte
